// Code generated by protoc-gen-go.
// source: frontend.proto
// DO NOT EDIT!

package msg_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Token struct {
	Sid              *string `protobuf:"bytes,1,req,name=sid" json:"sid,omitempty"`
	Ip               *string `protobuf:"bytes,2,req,name=ip" json:"ip,omitempty"`
	Port             *string `protobuf:"bytes,3,req,name=port" json:"port,omitempty"`
	ConnTime         *int64  `protobuf:"varint,4,req,name=conn_time" json:"conn_time,omitempty"`
	Pid              *string `protobuf:"bytes,5,req,name=pid" json:"pid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Token) Reset()                    { *m = Token{} }
func (m *Token) String() string            { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()               {}
func (*Token) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Token) GetSid() string {
	if m != nil && m.Sid != nil {
		return *m.Sid
	}
	return ""
}

func (m *Token) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

func (m *Token) GetPort() string {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return ""
}

func (m *Token) GetConnTime() int64 {
	if m != nil && m.ConnTime != nil {
		return *m.ConnTime
	}
	return 0
}

func (m *Token) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func init() {
	proto.RegisterType((*Token)(nil), "msg_proto.Token")
}

var fileDescriptor1 = []byte{
	// 115 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0x2b, 0xca, 0xcf,
	0x2b, 0x49, 0xcd, 0x4b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xcc, 0x2d, 0x4e, 0x8f,
	0x07, 0x33, 0x95, 0xfc, 0xb8, 0x58, 0x43, 0xf2, 0xb3, 0x53, 0xf3, 0x84, 0xb8, 0xb9, 0x98, 0x8b,
	0x33, 0x53, 0x24, 0x18, 0x15, 0x98, 0x34, 0x38, 0x85, 0xb8, 0xb8, 0x98, 0x32, 0x0b, 0x24, 0x98,
	0xc0, 0x6c, 0x1e, 0x2e, 0x96, 0x82, 0xfc, 0xa2, 0x12, 0x09, 0x66, 0x30, 0x4f, 0x90, 0x8b, 0x33,
	0x39, 0x3f, 0x2f, 0x2f, 0xbe, 0x24, 0x33, 0x37, 0x55, 0x82, 0x05, 0x28, 0xc4, 0x0c, 0xd2, 0x59,
	0x00, 0xd4, 0xc9, 0x0a, 0x92, 0x07, 0x04, 0x00, 0x00, 0xff, 0xff, 0x30, 0x22, 0xb8, 0xb9, 0x6b,
	0x00, 0x00, 0x00,
}
