// Code generated by protoc-gen-go.
// source: frontend.proto
// DO NOT EDIT!

package msg_proto

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

// 用于前端验证的token
type Token struct {
	Sid              *string `protobuf:"bytes,1,req,name=sid" json:"sid,omitempty"`
	Ip               *string `protobuf:"bytes,2,req,name=ip" json:"ip,omitempty"`
	Port             *string `protobuf:"bytes,3,req,name=port" json:"port,omitempty"`
	ConnTime         *int64  `protobuf:"varint,4,req,name=conn_time" json:"conn_time,omitempty"`
	Pid              *string `protobuf:"bytes,5,req,name=pid" json:"pid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}

func (m *Token) GetSid() string {
	if m != nil && m.Sid != nil {
		return *m.Sid
	}
	return ""
}

func (m *Token) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

func (m *Token) GetPort() string {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return ""
}

func (m *Token) GetConnTime() int64 {
	if m != nil && m.ConnTime != nil {
		return *m.ConnTime
	}
	return 0
}

func (m *Token) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func init() {
}
