// Code generated by protoc-gen-go.
// source: gate.proto
// DO NOT EDIT!

package msg_proto

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

// 登录请求
type RequestLogin struct {
	Username         *string `protobuf:"bytes,1,req,name=username" json:"username,omitempty"`
	Password         *string `protobuf:"bytes,2,req,name=password" json:"password,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RequestLogin) Reset()         { *m = RequestLogin{} }
func (m *RequestLogin) String() string { return proto.CompactTextString(m) }
func (*RequestLogin) ProtoMessage()    {}

func (m *RequestLogin) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *RequestLogin) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func init() {
}
